/*
 * SPDX-License-Identifier: MIT
 * SPDX-FileCopyrightText: 2026 The ferrumx-windows contributors
 * SPDX-FileCopyrightText: 2026 Cimari contributors
 */
package io.github.eggy03.cimari.shell.query;

import io.github.eggy03.cimari.entity.display.AbstractWin32DesktopMonitor;
import io.github.eggy03.cimari.entity.display.AbstractWin32VideoController;
import io.github.eggy03.cimari.entity.mainboard.AbstractWin32Baseboard;
import io.github.eggy03.cimari.entity.mainboard.AbstractWin32Bios;
import io.github.eggy03.cimari.entity.mainboard.AbstractWin32PortConnector;
import io.github.eggy03.cimari.entity.memory.AbstractWin32PhysicalMemory;
import io.github.eggy03.cimari.entity.network.AbstractWin32NetworkAdapter;
import io.github.eggy03.cimari.entity.network.AbstractWin32NetworkAdapterConfiguration;
import io.github.eggy03.cimari.entity.peripheral.AbstractWin32Battery;
import io.github.eggy03.cimari.entity.peripheral.AbstractWin32Printer;
import io.github.eggy03.cimari.entity.peripheral.AbstractWin32SoundDevice;
import io.github.eggy03.cimari.entity.processor.AbstractWin32CacheMemory;
import io.github.eggy03.cimari.entity.processor.AbstractWin32Processor;
import io.github.eggy03.cimari.entity.storage.AbstractWin32DiskDrive;
import io.github.eggy03.cimari.entity.storage.AbstractWin32DiskPartition;
import io.github.eggy03.cimari.entity.storage.AbstractWin32LogicalDisk;
import io.github.eggy03.cimari.entity.system.AbstractWin32ComputerSystem;
import io.github.eggy03.cimari.entity.system.AbstractWin32Environment;
import io.github.eggy03.cimari.entity.system.AbstractWin32OperatingSystem;
import io.github.eggy03.cimari.entity.system.AbstractWin32PnPEntity;
import io.github.eggy03.cimari.entity.system.AbstractWin32Process;
import io.github.eggy03.cimari.entity.user.AbstractWin32UserAccount;
import org.jspecify.annotations.NonNull;

import java.util.Objects;

/**
 * Enum representing the predefined WMI Win32 Class queries for the classes available in the {@code root/cimv2} namespace.
 * <p>
 * Each constant holds a PowerShell query that queries a specific class in the namespace
 * and returns the result in JSON format.
 * </p>
 *
 * @since 1.0.0
 */
/*
NOTE: Always use abstract WMI classes for generateQuery().
Do not replace them with concrete implementations since they're generated by Immutables and contain
a lot more methods than just property methods, all of which will be bundled with the generated query
 */
public enum Cimv2 {

    /**
     * Query to fetch the properties of {@code Win32_Battery} class
     *
     * @since 1.0.0
     */
    WIN32_BATTERY(generateQuery(AbstractWin32Battery.class)),

    /**
     * Query to fetch the properties of {@code Win32_DesktopMonitor} class
     *
     * @since 1.0.0
     */
    WIN32_DESKTOP_MONITOR(generateQuery(AbstractWin32DesktopMonitor.class)),

    /**
     * Query to fetch the properties of {@code Win32_VideoController} class
     *
     * @since 1.0.0
     */
    WIN32_VIDEO_CONTROLLER(generateQuery(AbstractWin32VideoController.class)),

    /**
     * Query to fetch the properties of {@code Win32_Processor} class
     *
     * @since 1.0.0
     */
    WIN32_PROCESSOR(generateQuery(AbstractWin32Processor.class)),

    /**
     * Query to fetch the properties of {@code Win32_CacheMemory} class
     *
     * @since 1.0.0
     */
    WIN32_CACHE_MEMORY(generateQuery(AbstractWin32CacheMemory.class)),

    /**
     * Query to fetch the properties of {@code Win32_AssociatedProcessorMemory} class in a custom object
     *
     * @since 1.0.0
     */
    WIN32_ASSOCIATED_PROCESSOR_MEMORY(
            "Get-CimInstance Win32_AssociatedProcessorMemory " +
                    "| ForEach-Object { [PSCustomObject]@{ CacheMemoryDeviceID = $_.Antecedent.DeviceID; ProcessorDeviceID = $_.Dependent.DeviceID } } " +
                    "| ConvertTo-Json"
    ),

    /**
     * Query to fetch the properties of {@code Win32_BIOS} class
     *
     * @since 1.0.0
     */
    WIN32_BIOS(generateQuery(AbstractWin32Bios.class)),

    /**
     * Query to fetch the properties of {@code Win32_Baseboard} class
     *
     * @since 1.0.0
     */
    WIN32_BASEBOARD(generateQuery(AbstractWin32Baseboard.class)),

    /**
     * Query to fetch the properties of {@code Win32_PortConnector} class
     *
     * @since 1.0.0
     */
    WIN32_PORT_CONNECTOR(generateQuery(AbstractWin32PortConnector.class)),

    /**
     * Query to fetch the properties of {@code Win32_PhysicalMemory} class
     *
     * @since 1.0.0
     */
    WIN32_PHYSICAL_MEMORY(generateQuery(AbstractWin32PhysicalMemory.class)),

    /**
     * Query to fetch the properties of {@code Win32_NetworkAdapter} class
     *
     * @since 1.0.0
     */
    WIN32_NETWORK_ADAPTER(generateQuery(AbstractWin32NetworkAdapter.class)),

    /**
     * Query to fetch the properties of {@code Win32_NetworkAdapterConfiguration} class
     *
     * @since 1.0.0
     */
    WIN32_NETWORK_ADAPTER_CONFIGURATION(generateQuery(AbstractWin32NetworkAdapterConfiguration.class)),

    /**
     * Query to fetch the properties of {@code Win32_NetworkAdapterSetting} in a custom object
     *
     * @since 1.0.0
     */
    WIN32_NETWORK_ADAPTER_SETTING(
            "Get-CimInstance Win32_NetworkAdapterSetting " +
                    "| ForEach-Object { [PSCustomObject]@{ NetworkAdapterDeviceID = $_.Element.DeviceID; NetworkAdapterConfigurationIndex = $_.Setting.Index } } " +
                    "| ConvertTo-Json"
    ),

    /**
     * Query to fetch the properties of {@code Win32_OperatingSystem} class
     *
     * @since 1.0.0
     */
    WIN32_OPERATING_SYSTEM(generateQuery(AbstractWin32OperatingSystem.class)),

    /**
     * Query to fetch the properties of {@code Win32_DiskDrive} class
     *
     * @since 1.0.0
     */
    WIN32_DISK_DRIVE(generateQuery(AbstractWin32DiskDrive.class)),

    /**
     * Query to fetch the properties of {@code Win32_DiskPartition} class
     *
     * @since 1.0.0
     */
    WIN32_DISK_PARTITION(generateQuery(AbstractWin32DiskPartition.class)),

    /**
     * Query to fetch the properties of {@code Win32_LogicalDisk} class
     *
     * @since 1.0.0
     */
    WIN32_LOGICAL_DISK(generateQuery(AbstractWin32LogicalDisk.class)),

    /**
     * Query to fetch the properties of {@code Win32_DiskDriveToDiskPartition} class in a custom object
     *
     * @since 1.0.0
     */
    WIN32_DISK_DRIVE_TO_DISK_PARTITION(
            "Get-CimInstance Win32_DiskDriveToDiskPartition " +
                    "| ForEach-Object { [PSCustomObject]@{ DiskDriveDeviceID = $_.Antecedent.DeviceID; DiskPartitionDeviceID = $_.Dependent.DeviceID } } " +
                    "| ConvertTo-Json"
    ),

    /**
     * Query to fetch the properties of {@code Win32_LogicalDiskToPartition} class in a custom object
     *
     * @since 1.0.0
     */
    WIN32_LOGICAL_DISK_TO_PARTITION(
            "Get-CimInstance Win32_LogicalDiskToPartition " +
                    "| ForEach-Object { [PSCustomObject]@{ DiskPartitionDeviceID = $_.Antecedent.DeviceID; LogicalDiskDeviceID = $_.Dependent.DeviceID } } " +
                    "| ConvertTo-Json"
    ),

    /**
     * Query to fetch the properties of {@code Win32_ComputerSystem} class
     *
     * @since 1.0.0
     */
    WIN32_COMPUTER_SYSTEM(generateQuery(AbstractWin32ComputerSystem.class)),

    /**
     * Query to fetch the properties of {@code Win32_Environment} class
     *
     * @since 1.0.0
     */
    WIN32_ENVIRONMENT(generateQuery(AbstractWin32Environment.class)),

    /**
     * Query to fetch the properties of {@code Win32_Printer} class
     *
     * @since 1.0.0
     */
    WIN32_PRINTER(generateQuery(AbstractWin32Printer.class)),

    /**
     * Query to fetch the properties of {@code Win32_UserAccount} class
     *
     * @since 1.0.0
     */
    WIN32_USER_ACCOUNT(generateQuery(AbstractWin32UserAccount.class)),

    /**
     * Query to fetch some select properties of {@code Win32_Process} class
     *
     * @since 1.0.0
     */
    WIN32_PROCESS(generateQuery(AbstractWin32Process.class)),

    /**
     * Query to fetch the properties of {@code Win32_SoundDevice} class
     *
     * @since 1.0.0
     */
    WIN32_SOUND_DEVICE(generateQuery(AbstractWin32SoundDevice.class)),

    /**
     * Query to fetch the properties of {@code Win32_PnPEntity} class
     */
    WIN32_PNP_ENTITY(generateQuery(AbstractWin32PnPEntity.class));

    private final @NonNull String query;

    Cimv2(@NonNull String query) {
        this.query = Objects.requireNonNull(query, "query cannot be null");
    }

    private static <T> @NonNull String generateQuery(@NonNull Class<T> wmiClass) {

        Objects.requireNonNull(wmiClass, "wmiClass cannot be null");

        return "Get-CimInstance -ClassName " + QueryUtility.getClassNameFromWmiClass(wmiClass) +
                " | Select-Object -Property " + QueryUtility.getPropertiesFromJsonProperty(wmiClass) +
                " | ConvertTo-Json";

    }

    public @NonNull String getQuery() {
        return this.query;
    }
}
