name: Deploy To Maven Central On Release
permissions:
  contents: read

on:
  release:
    types: [created]
  workflow_dispatch:  

env:
  JDK_VERSION: 25

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.JDK_VERSION }}

      # Configure Maven settings with OSSRH credentials
      - name: Configure Maven settings
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
        run: |
          mkdir -p $HOME/.m2
          cat <<EOF > $HOME/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>central</id>
                <username>${OSSRH_USERNAME}</username>
                <password>${OSSRH_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to OSSRH staging
        env:
          SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          SIGN_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn clean deploy -B -DskipTests
